development:
    dialect: mysql
    dir: db/migrations
    datasource: ${MYSQL_USER}:@tcp(127.0.0.1:${MYSQL_PORT})/caww?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=true

# Dummy setting
production:
    dialect: postgres
    dir: migrations/postgres
    datasource: dbname=myapp sslmode=disable
    table: migrations
